import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import StoreProvider from '@/lib/Provider/StoreProvider';
import Image from 'next/image';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Redux Typescript Tailwind',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={inter.style}>
      <StoreProvider>
        <body className="bg-background-950 font-montserrat">
          <Toaster
            toastOptions={{
              duration: 3000,
            }}
            position="top-right"
          />
          <main className="w-full relative min-h-screen">
            {children}
            <Image
              src="/illustrations/wave.svg"
              alt="Wave"
              width={200}
              height={200}
              className="w-full h-auto absolute z-0 bottom-0 left-0"
            />
          </main>
        </body>
      </StoreProvider>
    </html>
  );
}
